using MySale.AI.Domain;

namespace MySale.AI.Application.Abstractions;

// ---------------- Images for vision models ----------------

public sealed record AIImage(string MediaType, string Base64);

// ---------------- Model capabilities ----------------

public sealed class ModelCapabilities
{
    public bool Text { get; init; } = true;
    public bool Vision { get; init; }
    public bool Audio { get; init; }
    public bool StructuredOutput { get; init; } = true;
    /// <summary>"provider" (reported by the provider, e.g. Ollama /api/show) or "heuristic" (name-based).</summary>
    public string Source { get; init; } = "heuristic";
}

/// <summary>Optional: providers that can report a model's capabilities themselves (Ollama /api/show).</summary>
public interface ICapabilityProvider
{
    Task<ModelCapabilities?> GetCapabilitiesAsync(string model, CancellationToken ct);
}

// ---------------- Speech ----------------

public sealed class TranscriptionResult
{
    public string Text { get; init; } = string.Empty;
    public string? Language { get; init; }
    public double? DurationSeconds { get; init; }
    public string Provider { get; init; } = string.Empty;
    public string Model { get; init; } = string.Empty;
}

/// <summary>Speech-to-text engine. Independent of the chat model/provider.</summary>
public interface ISpeechToTextProvider
{
    Task<TranscriptionResult> TranscribeAsync(Stream audio, string fileName, string? language, CancellationToken ct = default);
}

/// <summary>Builds a speech-to-text engine for a configured provider (OpenAI, local Whisper server, …).</summary>
public interface ISpeechToTextProviderFactory
{
    bool Supports(string providerKind);
    ISpeechToTextProvider Create(ProviderConfig config, string model);
}

public sealed class SpeechSynthesisResult
{
    public required Stream Audio { get; init; }
    public string ContentType { get; init; } = "audio/mpeg";
}

/// <summary>Future: spoken answers. Not wired in this version (the UI uses the browser's speech synthesis).</summary>
public interface ITextToSpeechProvider
{
    Task<SpeechSynthesisResult> SynthesizeAsync(string text, string? language, string? voice, CancellationToken ct = default);
}

public sealed class SpeechException : Exception
{
    public SpeechException(string message, Exception? inner = null) : base(message, inner) { }
}

// ---------------- Attachments ----------------

/// <summary>Isolated binary storage. Keys are generated by the server; callers never pass paths.</summary>
public interface IAttachmentStore
{
    Task<string> SaveAsync(string companyId, string attachmentId, Stream content, CancellationToken ct);
    Task<Stream?> OpenReadAsync(string storageKey, CancellationToken ct);
    Task DeleteAsync(string storageKey, CancellationToken ct);
}

public interface IAttachmentRepository
{
    Task InsertAsync(Attachment attachment, CancellationToken ct);
    Task UpdateAsync(Attachment attachment, CancellationToken ct);
    Task<Attachment?> GetAsync(string id, CancellationToken ct);
    Task<List<Attachment>> GetManyAsync(IEnumerable<string> ids, CancellationToken ct);
    Task DeleteAsync(string id, CancellationToken ct);
    Task<List<Attachment>> ListExpiredAsync(DateTime now, int limit, CancellationToken ct);
}

public sealed class ScanResult
{
    public bool Clean { get; init; } = true;
    public string? Threat { get; init; }
    public string Scanner { get; init; } = "none";
}

/// <summary>Malware scanning hook. Default: no-op; ClamAV when configured.</summary>
public interface IFileScanner
{
    Task<ScanResult> ScanAsync(Stream content, CancellationToken ct);
}

public sealed class ExtractedContent
{
    public List<AttachmentChunk> Chunks { get; init; } = new();
    public AttachmentTable? Table { get; init; }
    public int? PageCount { get; init; }
    public bool Truncated { get; init; }
    public string? Summary { get; init; }
}

/// <summary>Extracts text / tables from one kind of file. Add a class to support a new format.</summary>
public interface IAttachmentProcessor
{
    bool CanProcess(string kind);
    Task<ExtractedContent> ProcessAsync(Stream content, string fileName, CancellationToken ct);
}
