<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
    <PackageReference Include="PdfPig" Version="0.1.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MySale.AI.Application\MySale.AI.Application.csproj" />
  </ItemGroup>
</Project>
